config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'osakes/index'
  # get 'osakes/show'
  # get 'osakes/edit'
  # get 'osakes/top'

  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  resources :osakes, only:[:index, :show, :edit, :create, :update, :destroy]
  resources :users, only:[:index, :show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/osake.rb
class Osake < ApplicationRecord
  # N:1の関係
  belongs_to :user

  # バリデーション設定
  validates :title, presence:true
  validates :body, presence:true, length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# ◆画像を扱えるようにする
has_one_attached :profile_image
# ◆1：Nの関係性
has_many :osakes, dependent: :destroy


 # バリデーション設定
  validates :name, presence: true, uniqueness: true , length: { minimum:2, maximum: 20}
  validates :introduction, length: { maximum: 50}


# ◆画像が存在しない場合no-imagに表示する画像をActiveStrageni格納
# その際、画像を引数でもらいリサイズできるようにしている
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top, :about]
  # before_action ApplicationCntrollerを実行する前に（＝全てのコントローラーの実行前に）
  # devise_controller?  デバイスに関わるがめんに行ったときに
  # configure_permitted_parameters　を行う
  # もしそれが、deviseのコントローラーだったら、configure_permitted_parametersを呼ぶ
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  protected

  # santitizer 消毒剤
  # devise_parameterを消毒して、新規登録がめんで、emailを受け取れるようにする
  # 最初は名前を登録にしたが、認証キーをemailからnameに変更したので、逆にemailの値を受け取れなくなった
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/osakes_controller.rb
class OsakesController < ApplicationController
  def index
    @osakes = Osake.all
    @osake = Osake.new
    @user = current_user
  end

  def create
    @osake = Osake.new(osake_params)
    @osake.user_id = current_user.id
    if @osake.save
      flash[:notice] = "You have created osake successfully."
      # book#showにリダイレクト
      redirect_to osake_path(@osake.id)
    else
      @osakes = Osake.all
      @osakenew = @osake
      @user = current_user
      render :index
    end
  end

  def show
    @osakenew = Osake.new
    @osake = Osake.find(params[:id])
    @user = @osake.user
  end

  def edit
    @osake = Osake.find(params[:id])
    unless @osake.user == current_user
      redirect_to osakes_path
    end
  end

  def update
    @osake = Osake.find(params[:id])
    if @osake.user != current_user
      redirect_to osakes_path
    else
      if @osake.update(osake_params)
        flash[:notice] = "You have updated osake successfully."
        # book#showにリダイレクト
        redirect_to osake_path(@osake.id)
      else
        render :edit
      end
    end
  end

  def destroy
    @osake = Osake.find(params[:id])
    if @osake.user != current_user
      redirect_to osakes_path
    else
      @osake.destroy
      redirect_to osakes_path
    end
  end

# ストロングパラメータ
  private

  def osake_params
    params.require(:osake).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @osakenew = Osake.new
  end

  def show
    @osakenew = Osake.new
    @user = User.find(params[:id])
    @osakes = @user.osakes
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    else
      if @user.update(user_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to user_path(@user.id)
      else
        render :edit
      end
    end
  end

private

def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<!--Homes#about-->
<div class = "container">
  <div class = "row">
  <div class = "mx-auto" cl-11 col-sm-10 col-lg-8 col-xl-6 >
      <h1>welcome to <strong><i class="fas fa-osake"></i>Osake_Club</strong> !!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<!--Homes#top-->
<div class = "container">
  <div class = "row">
  <div class = "mx-auto" cl-11 col-sm-10 col-lg-8 col-xl-6 >
      <h1>welcome to <strong><i class="fa-solid fa-glass-water"></i>Osake_Club</strong> !!</h1>
      <p>In <strong><i class="fa-solid fa-glass-water"></i>Osake_Club,</strong></p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various osake!</p>
      <%= link_to "Log in", new_user_session_path, class: 'btn btn-block btn-primary' %>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-block btn-success' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Osake_Club</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--◆bootstrap導入のため、tylesheet_link_tag　→ tylesheet_pack_tagに書き換え-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--FontAwesome読み込み-->
    <script src="https://kit.fontawesome.com/dc75088d57.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class = "container">
          <a class = "navbar-brand" href= "/"><span>Osake_Club</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
            <% if user_signed_in? %>
              <ul class = "navbar-nav ml-auto">
                <li class = "nav-item">
                  <%= link_to  user_path(current_user.id), class: 'nav-link text-light'  do %>
                    <i class="fas fa-home"></i>
                    <span>Home</span>
                  <% end %>
                </li>
                <li class = "nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i>
                    <span>Users</span>
                  <% end %>
                </li>
                <li class = "nav-item">
                  <%= link_to  osakes_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-osake-open"></i>
                    <span>Osakes</span>
                  <% end %>
                </li>
                <li class = "nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Log out</span>
                  <% end %>
                </li>
              </ul>
            <% else %>
              <ul class = "navbar-nav ml-auto">
                <li class = "nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>
                    <span>Home</span>
                    <% end %>
                </li>
                <li class = "nav-item">
                  <%= link_to  home_about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i>
                    <span>About</span>
                    <% end %>
                </li>
                <li class = "nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i>
                    <span>Sign up</span>
                    <% end %>
                </li>
                <li class = "nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i>
                    <span>Log in</span>
                    <% end %>
                </li>
               </ul>
              </nav>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <!--メッセージ-->
    <%= notice %>
    <%= alert %>
      <%= yield %>
    </main>

    <footer>
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
           <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/osakes/_error.html.erb
<% if model.errors.any? %>
  <div class ="errors">
      <h2 class = "errors_head"><%= model.errors.count %>errors prohibited this obj from being saved:</h2>
      <ul class = "errors_list">
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/osakes/_main.html.erb
<div class = "col-md-8 offset-md-1">
            <h2>Osakes</h2>
            <table class = "table table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan = "3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% osakes.each do |osake| %>
                        <tr>
                            <td>
                                <%= link_to user_path(osake.user) do %>
                                    <%= image_tag osake.user.get_profile_image(100,100) %>
                                <% end %>
                            </td>
                            <td><%= link_to osake.title, osake_path(osake.id) %></td>
                            <td><%= osake.body %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/osakes/_side.html.erb
<!--部分テンプレート　-->


<!--px-5左右のパディング5rem(基本の5倍)、px-sm-0小以上で左右のパディング0-->

<div class = "col-md-3">
  <h2>User info</h2>
  <p><%= image_tag user.get_profile_image(100,100) %></p>
  <table class = "table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class = "row">
    <%= link_to edit_user_path(user.id), class: 'btn btn-block btn-outline-secondary' do%>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class = "mt-3" >New osake</h2>
  <%= form_with model: osakenew, method: :post do |f| %>
    <%= f.label :title, 'Title' %><br />
    <%= f.text_field :title, autofocus: true, class: 'w-100' %><br />

    <%= f.label :body, 'Opinion' %><br />
    <%= f.text_area :body, autofocus: true, class: 'w-100' %><br />

    <%= f.submit "Create Osake", class: 'btn btn-success' %>

  <% end %>
</div>

app/views/osakes/edit.html.erb
<!--Books#edit-->
<div class = "container">
  <div class = "row">
    <!--smサイズ以上12 mdサイズ以上8 lgサイズ以上 左右のパディングを3rem sm以上で左右のパディング0　水平にセンタリング-->
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Osake</h1>
      <%= render 'error', model: @osake %>
      <%= form_with model:@osake do |f| %>
        <%= f.label :title, 'Title' %><br/>
        <%= f.text_field :title, autofocus:true %><br/>
        <%= f.label :body, 'Opinion' %><br/>
        <%= f.text_area :body, autofocus:true %><br/>
        <%= f.submit 'Update Osake', class: 'btn btn-success'  %><br/>

      <% end %>

      <%= link_to "Show", osake_path(@osake.id) %>
      |
      <%= link_to "Back", osakes_path %>
    </div>
  </div>
</div>

app/views/osakes/index.html.erb
<!--Books#index-->
<%= render 'error', model: @osake %>
<div class ="container px-5 px-sm-0">
  <div class = "row">
    <%= render 'side', user: @user, osakes: @osakes, osakenew: @osake %>
    <%= render 'main', osakes: @osakes %>
  </div>
</div>

app/views/osakes/show.html.erb
<!--Books#show-->



  <div class ="container px-5 px-sm-0">
    <div class = "row">
       <%= render 'side', user: @user, osakenew: @osakenew, osake: @osake %>
      <div class = "col-md-8 offset-md-1">
        <h2>osake detail</h2>

        <table class = "table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@osake.user_id) do %>
                  <%= image_tag @user.get_profile_image(100,100) %></br>
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @osake.title, osake_path(@osake.id) %></td>
              <td><%= @osake.body %></td>
              <%if @osake.user == current_user %>
                <td><%= link_to "Edit", edit_osake_path(@osake.id), class: 'btn btn-success' %></td>
                <td><%= link_to "Destroy", osake_path(@osake.id), method: :delete, "data-confirm" => "本当に消しますか？" ,class: 'btn btn-danger'  %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/users/edit.html.erb
<!--Users#edit-->
<div class ="container px-5 px-sm-0">
  <div class = "row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'osakes/error', model: @user, method: :patch %>
      <%= form_with model:@user do |f| %>
        <%= f.label :name, 'Name' %><br/>
        <%= f.text_field :name, autofocus:true %><br/>
        <%= f.label :profile_image, 'Image' %><br/>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br/>
        <%= f.label :introduction, 'introduction' %><br/>
        <%= f.text_area :introduction, autofocus:true %><br/>
        <%= f.submit 'Update User' , class: 'btn btn-secondary' %><br/>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--Users#index-->
 <div class ="container px-5 px-sm-0">
    <div class = "row">
      <%= render 'osakes/side', user: @user, osakenew: @osakenew %>
      <div class = "col-md-8 offset-md-1">
          <h2>Osakes</h2>
            <table class = "table table-hover">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th colspan = "3"></th>
                    </tr>
                </thead>
                <tbody>

                    <% @users.each do |user| %>
                        <tr>
                            <td><%= image_tag user.get_profile_image(100,100) %></td>
                            <td><%= user.name %></td>
                            <td><%= link_to "Show", user_path(user.id) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<!--User#show-->
 <div class ="container px-5 px-sm-0">
    <div class = "row">
        <%= render 'osakes/side', user: @user, osakes: @osakes, osakenew: @osakenew %>
        <%= render 'osakes/main', osakes: @osakes %>
    </div>
</div>